# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1480, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nhomCoPhieuLabel = QtWidgets.QLabel(self.centralwidget)
        self.nhomCoPhieuLabel.setObjectName("nhomCoPhieuLabel")

        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 485, 18))
        self.menubar.setObjectName("menubar")
        self.menuNhonCoPhieu = QtWidgets.QMenu(self.menubar)
        self.menuNhonCoPhieu.setObjectName("menuNhonCoPhieu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuDaMua = QtWidgets.QAction(MainWindow)
        self.menuDaMua.setObjectName("menuDaMua")
        self.menuVn100 = QtWidgets.QAction(MainWindow)
        self.menuVn100.setObjectName("menuVn")
        self.menuNganHang = QtWidgets.QAction(MainWindow)
        self.menuNganHang.setObjectName("menuNganHang")
        self.menuNangLuong = QtWidgets.QAction(MainWindow)
        self.menuNangLuong.setObjectName("menuNangLuong")
        self.menuSanXuat = QtWidgets.QAction(MainWindow)
        self.menuSanXuat.setObjectName("menuSanXuat")
        self.menuCongNgheThongTin = QtWidgets.QAction(MainWindow)
        self.menuCongNgheThongTin.setObjectName("menuCongNgheThongTin")
        self.menuLuaChonBoiCacQuy = QtWidgets.QAction(MainWindow)
        self.menuLuaChonBoiCacQuy.setObjectName("menuLuaChonBoiCacQuy")
        self.menuNhonCoPhieu.addAction(self.menuDaMua)
        self.menuNhonCoPhieu.addAction(self.menuVn100)
        self.menuNhonCoPhieu.addAction(self.menuNganHang)
        self.menuNhonCoPhieu.addAction(self.menuNangLuong)
        self.menuNhonCoPhieu.addAction(self.menuSanXuat)
        self.menuNhonCoPhieu.addAction(self.menuCongNgheThongTin)
        self.menuNhonCoPhieu.addAction(self.menuLuaChonBoiCacQuy)
        self.menubar.addAction(self.menuNhonCoPhieu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuNhonCoPhieu.setTitle(_translate("MainWindow", "Chọn cổ phiếu"))
        self.menuDaMua.setText(_translate("MainWindow", "Cổ phiếu đã mua"))
        self.menuDaMua.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.menuVn100.setText(_translate("MainWindow", "VN100"))
        self.menuVn100.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.menuNganHang.setText(_translate("MainWindow", "Ngân hàng"))
        self.menuNganHang.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.menuNangLuong.setText(_translate("MainWindow", "Năng lượng"))
        self.menuNangLuong.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.menuSanXuat.setText(_translate("MainWindow", "Sản xuất"))
        self.menuSanXuat.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.menuCongNgheThongTin.setText(_translate("MainWindow", "CNTT"))
        self.menuCongNgheThongTin.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.menuLuaChonBoiCacQuy.setText(_translate("MainWindow", "Lựa chọn bởi các quỹ"))
        self.menuLuaChonBoiCacQuy.setShortcut(_translate("MainWindow", "Ctrl+Q"))




